name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Run PSScriptAnalyzer with settings
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path scripts/ps -Recurse -Settings ./.config/PSScriptAnalyzerSettings.psd1
